backend:
  name: gitlab
  repo: rick/ampDocs # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: 0ed862717ca6d0d40580c6c0594c391a005a9d3f944612a36728407e0518d067 # Application ID from your GitLab settings
  api_root: https://git.cfost.org/api/v4
  base_url: https://git.cfost.org
  auth_endpoint: oauth/authorize

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8080/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']

site_url: http://localhost:8080

public_folder: "docs/uploads"
media_folder: "docs/images"
publish_mode: editorial_workflow

collections:
  - name: "gettingStarted" # Used in routes, e.g., /admin/collections/blog
    label: "Getting Started" # Used in the UI
    folder: "docs/Getting Started" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "organization" # Used in routes, e.g., /admin/collections/blog
    label: "Organization" # Used in the UI
    folder: "docs/Organization" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "campaign" # Used in routes, e.g., /admin/collections/blog
    label: "Campaign" # Used in the UI
    folder: "docs/Campaign" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "targeting" # Used in routes, e.g., /admin/collections/blog
    label: "Targeting" # Used in the UI
    folder: "docs/Targeting" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "assets" # Used in routes, e.g., /admin/collections/blog
    label: "Assets" # Used in the UI
    folder: "docs/Assets" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "campaignSettings" # Used in routes, e.g., /admin/collections/blog
    label: "Campaign Settings" # Used in the UI
    folder: "docs/Campaign Settings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "scripts" # Used in routes, e.g., /admin/collections/blog
    label: "Scripts" # Used in the UI
    folder: "docs/Scripts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "phonebank" # Used in routes, e.g., /admin/collections/blog
    label: "Phonebank" # Used in the UI
    folder: "docs/Phonebank" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "texting" # Used in routes, e.g., /admin/collections/blog
    label: "Texting" # Used in the UI
    folder: "docs/Texting" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "docs"}
      - {label: "Body", name: "body", widget: "markdown"}
